const CONSTANTS = {};

CONSTANTS.ENDPOINT = {};
CONSTANTS.ENDPOINT.TESTURL = "http://openlibrary.org/people/george08/lists.json";

CONSTANTS.ENDPOINT.FAKETOKEN = "/api/FakeToken/Test";

CONSTANTS.ENDPOINT.USERS = {};
CONSTANTS.ENDPOINT.USERS.BASE = "/api/Users";
CONSTANTS.ENDPOINT.USERS.LOGIN = "/login";
CONSTANTS.ENDPOINT.USERS.GETALL = "/GetAll";
CONSTANTS.ENDPOINT.USERS.GETONE = "/GetOne";
CONSTANTS.ENDPOINT.USERS.UPDATE = "/Update";
CONSTANTS.ENDPOINT.USERS.CREATE = "/Create";
CONSTANTS.ENDPOINT.USERS.REFRESHTOKEN = "/RefreshToken";

CONSTANTS.ENDPOINT.ROLES = {};
CONSTANTS.ENDPOINT.ROLES.BASE = "/api/Roles";
CONSTANTS.ENDPOINT.ROLES.GETJSON = "/GetJson";

CONSTANTS.ENDPOINT.NEWS = {};
CONSTANTS.ENDPOINT.NEWS.BASE = "/api/News";
CONSTANTS.ENDPOINT.NEWS.GETALL = "/GetAll";
CONSTANTS.ENDPOINT.NEWS.GETONE = "/GetOne";
CONSTANTS.ENDPOINT.NEWS.UPDATE = "/Update";
CONSTANTS.ENDPOINT.NEWS.CREATE = "/Create";


export default CONSTANTS;