const CONSTANTS = {};

CONSTANTS.ENDPOINT = {};
CONSTANTS.ENDPOINT.TESTURL = "http://openlibrary.org/people/george08/lists.json";

CONSTANTS.ENDPOINT.USERS = {};
CONSTANTS.ENDPOINT.USERS.BASE = "/api/Users";
CONSTANTS.ENDPOINT.USERS.LOGIN = "/login";
CONSTANTS.ENDPOINT.USERS.GETALL = "/GetAll";
CONSTANTS.ENDPOINT.USERS.REFRESHTOKEN = "/RefreshToken";



export default CONSTANTS;