---
apiVersion: v1
kind: Pod
metadata:
  name: zlinebot-pod
  labels:
    app: zlinebotApp
spec:
  containers:
    - name: zlinebot-container
      image: dyco/zlinebot
      ports:
        - containerPort: 80
  hostAliases:
    - ip: "172.17.0.6"
---          
kind: Pod
metadata:
  name: some-postgres
  labels:
    name: some-postgres
spec:
  containers:
    - image: launcher.gcr.io/google/postgresql9
      name: postgres
      env:
        - name: "postgres"
          value: "p12345"
      volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: data
  hostAliases:
    - ip: "172.17.0.7"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
---
# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi